version: '2'
services:
    frontend:
        image: phaul-in-container
        container_name: frontend
        command: "/root/start.sh frontend"
        networks:
            - phaul_test
        ports:
            - 8081:8081
        privileged: true
        tmpfs:
            - /run
        volumes:
            - ./image:/root/image

    frontend2:
        image: phaul-in-container
        container_name: frontend2
        networks:
            - phaul_test
        ports:
            - 8082:8081
        privileged: true
        tmpfs:
            - /run
        volumes:
            - ./image:/root/image
        command: "tail -f /dev/null"
        

    backend:
        image: phaul-in-container
        container_name: backend
        command: "/root/start.sh backend"
        networks:
            - phaul_test
        ports: 
            - 9000:9000
    
    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        networks:
            - phaul_test
        ports: 
            - 9411:9411

networks:
    phaul_test:
        driver: bridge
